---

- hosts: all
  become: true
  tasks:
  
  - name: update package  repository and install nginx & ssh
    package:
      name:
        -  "{{ package_nginx }}"
        -  "{{ package_ssh }}"
      state: latest      
      update-cache: true


