---

- hosts: all
  become: true
  tasks:
  
  - name: update apt repository
    apt:
      update-cache: true
          
  - name: install nginx package
    apt:
      name: nginx
      state: latest

  - name: install ssh package
    apt:
      name: ssh
      state: latest
