---

- hosts: all
  become: true
  roles:
    - default
  

- hosts: web_server
  become: true
  name: add webserver role and tasks
  roles:
    - web_server

- hosts: mysql
  become: true
  tasks:
    - name: install website database
      apt:
        name: mysql-server
